//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IcsFresh.OpenApi.Ef
{
    using System;
    using System.Collections.Generic;
    
    public partial class CoreLanguage
    {
        public string CoreLanguageId { get; set; }
        public int MenuId { get; set; }
        public string Value { get; set; }
        public string Culture { get; set; }
    }
}
