//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IcsFresh.OpenApi.Ef
{
    using System;
    using System.Collections.Generic;
    
    public partial class CoreTableMetaData
    {
        public string TableName { get; set; }
        public string FieldName { get; set; }
        public bool IsPrimaryKey { get; set; }
        public int Sequence { get; set; }
        public string Label { get; set; }
        public string Type { get; set; }
        public bool IsRequired { get; set; }
        public string CoreDataSourceId { get; set; }
        public string PlaceHolder { get; set; }
        public string DefaultValue { get; set; }
        public bool IsSearchFilter { get; set; }
        public bool IsVisibleInSearchResult { get; set; }
        public bool IsVisibleInForm { get; set; }
        public bool IsInsertDisabled { get; set; }
        public bool IsUpdateDisabled { get; set; }
        public string ValueUI { get; set; }
    }
}
