//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IcsFresh.OpenApi.Ef
{
    using System;
    using System.Collections.Generic;
    
    public partial class CustomerOrderTemplate
    {
        public System.Guid Id { get; set; }
        public string Name { get; set; }
        public string CustomerCode { get; set; }
        public string TemplateCode { get; set; }
        public int Seq { get; set; }
    
        public virtual Customer Customer { get; set; }
        public virtual OrderTemplate OrderTemplate { get; set; }
    }
}
