//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IcsFresh.OpenApi.Ef
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderTemplateDetial
    {
        public string TemplateCode { get; set; }
        public string ProductCode { get; set; }
        public string Sequence { get; set; }
    
        public virtual OrderTamplate OrderTamplate { get; set; }
        public virtual Product Product { get; set; }
    }
}
