//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IcsFresh.OpenApi.Ef
{
    using System;
    using System.Collections.Generic;
    
    public partial class vOrderSummary
    {
        public System.Guid Id { get; set; }
        public string TemplateCode { get; set; }
        public string TemplateName { get; set; }
        public Nullable<System.DateTime> DeliveryDate { get; set; }
        public string ProductCode { get; set; }
        public string ProductName { get; set; }
        public string SupplierCode { get; set; }
        public string CategoryCode { get; set; }
        public string Quantity { get; set; }
        public string UnitMeter { get; set; }
        public Nullable<decimal> UnitPrice { get; set; }
        public string UnitName { get; set; }
    }
}
